package com.sailmi.sailplat.foundation.domain;
// Generated 2019-2-17 20:45:19 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblDistrictsGoodsclass generated by hbm2java
 */
@Entity
@Table(name = "tbl_districts_goodsclass", catalog = "sailplat")
public class DistrictsGoodsclass implements java.io.Serializable {

	private Long id;
	private Districts tblDistricts;
	private GoodsClass tblGoodsclass;
	private String desc;
	private Date createDate;
	private Date modifyDate;

	public DistrictsGoodsclass() {
	}

	public DistrictsGoodsclass(Districts tblDistricts, GoodsClass tblGoodsclass, String desc, Date createDate,
			Date modifyDate) {
		this.tblDistricts = tblDistricts;
		this.tblGoodsclass = tblGoodsclass;
		this.desc = desc;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "districtsId")
	public Districts getTblDistricts() {
		return this.tblDistricts;
	}

	public void setTblDistricts(Districts tblDistricts) {
		this.tblDistricts = tblDistricts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goodsClassId")
	public GoodsClass getTblGoodsclass() {
		return this.tblGoodsclass;
	}

	public void setTblGoodsclass(GoodsClass tblGoodsclass) {
		this.tblGoodsclass = tblGoodsclass;
	}

	@Column(name = "desc", length = 50)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifyDate", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
