package com.sailmi.sailplat.foundation.domain;
// Generated 2019-2-17 20:45:19 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblDistricts generated by hbm2java
 */
@Entity
@Table(name = "tbl_districts", catalog = "sailplat")
public class Districts implements java.io.Serializable {

	private Long id;
	private String districtName;
	private byte districtType;
	private String districtDesc;
	private Date createDate;
	private Date modifyDate;
	private Set<DistrictsGoodsclass> tblDistrictsGoodsclasses = new HashSet<DistrictsGoodsclass>(0);
	private Set<DistrictsArticle> tblDistrictsArticles = new HashSet<DistrictsArticle>(0);

	public Districts() {
	}

	public Districts(String districtName, byte districtType, Date createDate, Date modifyDate) {
		this.districtName = districtName;
		this.districtType = districtType;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Districts(String districtName, byte districtType, String districtDesc, Date createDate, Date modifyDate,
			Set<DistrictsGoodsclass> tblDistrictsGoodsclasses, Set<DistrictsArticle> tblDistrictsArticles) {
		this.districtName = districtName;
		this.districtType = districtType;
		this.districtDesc = districtDesc;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.tblDistrictsGoodsclasses = tblDistrictsGoodsclasses;
		this.tblDistrictsArticles = tblDistrictsArticles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "districtName", nullable = false, length = 50)
	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	@Column(name = "districtType", nullable = false)
	public byte getDistrictType() {
		return this.districtType;
	}

	public void setDistrictType(byte districtType) {
		this.districtType = districtType;
	}

	@Column(name = "districtDesc", length = 200)
	public String getDistrictDesc() {
		return this.districtDesc;
	}

	public void setDistrictDesc(String districtDesc) {
		this.districtDesc = districtDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifyDate", nullable = false, length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDistricts")
	public Set<DistrictsGoodsclass> getTblDistrictsGoodsclasses() {
		return this.tblDistrictsGoodsclasses;
	}

	public void setTblDistrictsGoodsclasses(Set<DistrictsGoodsclass> tblDistrictsGoodsclasses) {
		this.tblDistrictsGoodsclasses = tblDistrictsGoodsclasses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblDistricts")
	public Set<DistrictsArticle> getTblDistrictsArticles() {
		return this.tblDistrictsArticles;
	}

	public void setTblDistrictsArticles(Set<DistrictsArticle> tblDistrictsArticles) {
		this.tblDistrictsArticles = tblDistrictsArticles;
	}

}
