package com.sailmi.sailplat.foundation.domain;
// Generated 2019-3-19 16:57:19 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblEnterprise generated by hbm2java
 */
@Entity
@Table(name = "tbl_enterprise", catalog = "sailplat")
public class Enterprise implements java.io.Serializable {

	private Integer id;
	private User tblUser;
	private String enName;
	private String enCode;
	private String enAddr;
	private String enOwner;
	private Boolean enIsauth;
	private Boolean enIsvalid;
	private Date enValiddate;
	private String enDesc;
	private Date createDate;
	private Date modifyDate;

	public Enterprise() {
	}

	public Enterprise(User tblUser, String enName, String enCode, String enAddr, String enOwner, Boolean enIsauth,
			Boolean enIsvalid, Date enValiddate, String enDesc, Date createDate, Date modifyDate) {
		this.tblUser = tblUser;
		this.enName = enName;
		this.enCode = enCode;
		this.enAddr = enAddr;
		this.enOwner = enOwner;
		this.enIsauth = enIsauth;
		this.enIsvalid = enIsvalid;
		this.enValiddate = enValiddate;
		this.enDesc = enDesc;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "en_creator")
	public User getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(User tblUser) {
		this.tblUser = tblUser;
	}

	@Column(name = "en_name", length = 50)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@Column(name = "en_code", length = 50)
	public String getEnCode() {
		return this.enCode;
	}

	public void setEnCode(String enCode) {
		this.enCode = enCode;
	}

	@Column(name = "en_addr", length = 100)
	public String getEnAddr() {
		return this.enAddr;
	}

	public void setEnAddr(String enAddr) {
		this.enAddr = enAddr;
	}

	@Column(name = "en_owner", length = 100)
	public String getEnOwner() {
		return this.enOwner;
	}

	public void setEnOwner(String enOwner) {
		this.enOwner = enOwner;
	}

	@Column(name = "en_isauth")
	public Boolean getEnIsauth() {
		return this.enIsauth;
	}

	public void setEnIsauth(Boolean enIsauth) {
		this.enIsauth = enIsauth;
	}

	@Column(name = "en_isvalid")
	public Boolean getEnIsvalid() {
		return this.enIsvalid;
	}

	public void setEnIsvalid(Boolean enIsvalid) {
		this.enIsvalid = enIsvalid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "en_validdate", length = 19)
	public Date getEnValiddate() {
		return this.enValiddate;
	}

	public void setEnValiddate(Date enValiddate) {
		this.enValiddate = enValiddate;
	}

	@Column(name = "en_desc", length = 50)
	public String getEnDesc() {
		return this.enDesc;
	}

	public void setEnDesc(String enDesc) {
		this.enDesc = enDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
