package com.sailmi.sailplat.foundation.domain;
// Generated 2019-2-17 20:45:19 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblGoodsArticle generated by hbm2java
 */
@Entity
@Table(name = "tbl_goods_article", catalog = "sailplat")
public class GoodsArticle implements java.io.Serializable {

	private Long id;
	private Article tblArticle;
	private Goods tblGoods;
	private GoodsclassArticleClass tblGoodsclassArticleClass;
	private String desc;
	private Date createDate;
	private Date modifyDate;

	public GoodsArticle() {
	}

	public GoodsArticle(Article tblArticle, Goods tblGoods,
			GoodsclassArticleClass tblGoodsclassArticleClass, String desc, Date createDate, Date modifyDate) {
		this.tblArticle = tblArticle;
		this.tblGoods = tblGoods;
		this.tblGoodsclassArticleClass = tblGoodsclassArticleClass;
		this.desc = desc;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "articleId", nullable = false)
	public Article getTblArticle() {
		return this.tblArticle;
	}

	public void setTblArticle(Article tblArticle) {
		this.tblArticle = tblArticle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goodsId", nullable = false)
	public Goods getTblGoods() {
		return this.tblGoods;
	}

	public void setTblGoods(Goods tblGoods) {
		this.tblGoods = tblGoods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classId", nullable = false)
	public GoodsclassArticleClass getTblGoodsclassArticleClass() {
		return this.tblGoodsclassArticleClass;
	}

	public void setTblGoodsclassArticleClass(GoodsclassArticleClass tblGoodsclassArticleClass) {
		this.tblGoodsclassArticleClass = tblGoodsclassArticleClass;
	}

	@Column(name = "desc", nullable = false, length = 50)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifyDate", nullable = false, length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
