package com.sailmi.sailplat.foundation.domain;
// Generated 2019-2-17 20:45:19 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUserArticleClass generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_article_class", catalog = "sailplat")
public class UserArticleClass implements java.io.Serializable {

	private Long id;
	private User tblUser;
	private Long className;
	private Long parentId;
	private String classDesc;
	private Date createDate;
	private Date modifyDate;
	private Set<UserArticle> tblUserArticles = new HashSet<UserArticle>(0);

	public UserArticleClass() {
	}

	public UserArticleClass(User tblUser, Long className, Long parentId, String classDesc, Date createDate,
			Date modifyDate, Set<UserArticle> tblUserArticles) {
		this.tblUser = tblUser;
		this.className = className;
		this.parentId = parentId;
		this.classDesc = classDesc;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.tblUserArticles = tblUserArticles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public User getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(User tblUser) {
		this.tblUser = tblUser;
	}

	@Column(name = "className")
	public Long getClassName() {
		return this.className;
	}

	public void setClassName(Long className) {
		this.className = className;
	}

	@Column(name = "parentId")
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	@Column(name = "classDesc", length = 100)
	public String getClassDesc() {
		return this.classDesc;
	}

	public void setClassDesc(String classDesc) {
		this.classDesc = classDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifyDate", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblUserArticleClass")
	public Set<UserArticle> getTblUserArticles() {
		return this.tblUserArticles;
	}

	public void setTblUserArticles(Set<UserArticle> tblUserArticles) {
		this.tblUserArticles = tblUserArticles;
	}

}
