package com.sailmi.sailplat.foundation.domain;
// Generated 2019-2-17 20:45:19 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblUserArticle generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_article", catalog = "sailplat")
public class UserArticle implements java.io.Serializable {

	private Long id;
	private Article tblArticle;
	private User tblUser;
	private UserArticleClass tblUserArticleClass;
	private String userArticleTag;
	private Byte userArticleType;
	private String userArticleDesc;

	public UserArticle() {
	}

	public UserArticle(Article tblArticle, User tblUser, UserArticleClass tblUserArticleClass) {
		this.tblArticle = tblArticle;
		this.tblUser = tblUser;
		this.tblUserArticleClass = tblUserArticleClass;
	}

	public UserArticle(Article tblArticle, User tblUser, UserArticleClass tblUserArticleClass,
			String userArticleTag, Byte userArticleType, String userArticleDesc) {
		this.tblArticle = tblArticle;
		this.tblUser = tblUser;
		this.tblUserArticleClass = tblUserArticleClass;
		this.userArticleTag = userArticleTag;
		this.userArticleType = userArticleType;
		this.userArticleDesc = userArticleDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "articleId", nullable = false)
	public Article getTblArticle() {
		return this.tblArticle;
	}

	public void setTblArticle(Article tblArticle) {
		this.tblArticle = tblArticle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public User getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(User tblUser) {
		this.tblUser = tblUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userArticleClassId", nullable = false)
	public UserArticleClass getTblUserArticleClass() {
		return this.tblUserArticleClass;
	}

	public void setTblUserArticleClass(UserArticleClass tblUserArticleClass) {
		this.tblUserArticleClass = tblUserArticleClass;
	}

	@Column(name = "userArticleTag", length = 500)
	public String getUserArticleTag() {
		return this.userArticleTag;
	}

	public void setUserArticleTag(String userArticleTag) {
		this.userArticleTag = userArticleTag;
	}

	@Column(name = "userArticleType")
	public Byte getUserArticleType() {
		return this.userArticleType;
	}

	public void setUserArticleType(Byte userArticleType) {
		this.userArticleType = userArticleType;
	}

	@Column(name = "userArticleDesc", length = 100)
	public String getUserArticleDesc() {
		return this.userArticleDesc;
	}

	public void setUserArticleDesc(String userArticleDesc) {
		this.userArticleDesc = userArticleDesc;
	}

}
